

export const TASK_PROGRESS = {
    PENDING: 1,
    PROGRESS: 2,
    COMPLETED: 3
};

export const TASK_STATUS = {
    ASSIGNED: 1,
    UNASSIGNED: 2
};

export const MESSAGE = {
    DATABASE_ERROR: "DATABASE_ERROR",
    NO_DATA_FOUND: "NO_DATA_FOUND",
    SERVER_ERROR: "SERVER_ERROR",
    INCORRECT_EMAIL_OR_PASSWORD: "INCORRECT_EMAIL_OR_PASSWORD",
    USER_ALREADY_EXIST: "USER_ALREADY_EXIST",
    INVALID_DATA: "INVALID_DATA",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS"
}
